MeetingsManagement/Controllers/MeetingsController.cs
using MeetingsManagementWeb.Data;
using MeetingsManagementWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MeetingsManagementWeb.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _dbContext;
        public MeetingsController(UserManager<ApplicationUser> userManager, ApplicationDbContext dbContext)
        {
            _userManager = userManager;
            _dbContext = dbContext;
        }
        [Authorize]
        public IActionResult Schedule()
        {
            return View();
        }
        [Authorize]
        public IActionResult Reschedule(int id)
        {
            string? userId = _userManager.GetUserId(HttpContext.User);
            if (string.IsNullOrEmpty(userId))
                return Unauthorized();
            var meeting = _dbContext.Meetings.Find(id);
            if (meeting is null)
                return NotFound();
            if (meeting.UserId != userId)
                return Unauthorized();
            return View("Schedule", meeting);
        }
        [Authorize, HttpPost]
        public IActionResult Schedule(Meeting meeting)
        {
            meeting.UserId = _userManager.GetUserId(HttpContext.User)!;
            if (!ModelState.IsValid)
                return View();
            if (meeting.StartTime < DateTime.Now) {
                ModelState.AddModelError("StartTime", "The start time of meeting cannot be earlier the current time.");
                return View();
            }
            if (meeting.EndTime < meeting.StartTime)
            {
                ModelState.AddModelError("EndTime", "The end time cannot be earlier than the start time.");
                return View();
            }
            if (meeting.Id > 0)
                _dbContext.Update(meeting);
            else
                _dbContext.Add(meeting);
            _dbContext.SaveChanges();
            return RedirectToRoute("MeetingReminders", new { meeting.Id });
        }
        [Authorize]
        public IActionResult Show()
        {
            var userId = _userManager.GetUserId(HttpContext.User)!;
            return View(_dbContext.Meetings.Where(m => m.UserId == userId).OrderBy(meeting => meeting.StartTime).ToList());
        }
        [Authorize, HttpDelete]
        public IActionResult Delete([FromBody] int id)
        {
            var meeting = _dbContext.Meetings.FirstOrDefault(m => m.Id == id);
            if (meeting is null)
                return NotFound();
            _dbContext.Meetings.Remove(meeting);
            _dbContext.SaveChanges();
            return NoContent();
        }
    }
}

MeetingsManagement/Controllers/ProfileController.cs
using MeetingsManagementWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MeetingsManagementWeb.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public ProfileController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;
            if (user is null)
                return RedirectToAction("Index", "Home");
            return View(user.Nickname! as object);
        }
    }
}

MeetingsManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@{
    bool isAnonymous = (User.Identity is null || !User.Identity.IsAuthenticated);
    bool isHome = "Home".Equals(ViewData["Title"]);
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meetings Management</title>
    <link rel="stylesheet" href="~/css/normalize.css" />
    <link rel="stylesheet" href="~/css/main-style.css?2023-10-29 12:18" />
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <div class="container">
            <div class="left">
                <h1><a asp-controller="Home" asp-action="Index" style="color:inherit">Meeting Management</a></h1>
                <ul>
                    @if (!isAnonymous)
                    {
                        <li><a asp-controller="Meetings" asp-action="Show">Meetings</a></li>
                        <li><a asp-controller="Meetings" asp-action="Schedule">Schedule</a></li>
                    }
                </ul>
            </div>
            <div class="right">
                <ul>
                    @if (isAnonymous)
                    {
                        <li><a asp-controller="Account" asp-action="SignUp">Sign up</a></li>
                        <li><a asp-controller="Account" asp-action="LogIn">Log in</a></li>
                    } else
                    {
                        <li><a asp-controller="Profile" asp-action="Index">Profile</a></li>
                        <li><a asp-controller="Account" asp-action="LogOut">Log out</a></li>
                    }
                </ul>
            </div>
        </div>
    </header>
    <div class="content">
        @if (!isAnonymous || !isHome)
        {
            <h2>@ViewData["ContentTitle"]</h2>
        }
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @if (!isAnonymous)
    {
        <script src="~/js/log-out.js"></script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>